# Importações e mapeamento

### Importando bibliotecas

In [1]:
import kagglehub
import pandas as pd

c:\Users\Sérgio\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### Mapeamento do path para importação do arquivo CSV via WEB

In [2]:
path = kagglehub.dataset_download("namespaiva/base-varejo")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\Sérgio\.cache\kagglehub\datasets\namespaiva\base-varejo\versions\1

### Importando o arquivo CSV via WEB

In [3]:
df = pd.read_csv(path + "/Base Varejo.csv", sep=";", encoding="utf-8")

### Importando o arquivo CSV local (caso a importação via WEB esteja indisponível)

In [4]:
# df = pd.read_csv("Base Varejo.csv", sep=";", encoding="utf-8")

# Obs.: Baixar o dataset do Kaggle e colocar na mesma pasta do script, caso não queira usar a biblioteca kagglehub.
# em https://www.kaggle.com/datasets/namespaiva/base-varejo/data

# Informações do arquivo CSV

### Exibindo as primeiras 5 linhas

In [5]:
df.head()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

### Exibindo as últimas 5 linhas

In [6]:
df.tail()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP,NaN,NaN,NaN,NaN
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA,NaN,NaN,NaN,NaN
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ,NaN,NaN,NaN,NaN
829998,19/08/2022,919822,155,F,2,0,B,214,ALIMENTOS,CEBOLA,NaN,NaN,NaN,NaN
829999,19/08/2022,919822,155,F,2,0,B,59,ALIMENTOS,SALGADINHO,NaN,NaN,NaN,NaN

### Exibindo os nomes das colunas

In [7]:
df.columns

Index(['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG',
       'PR_ID', 'PR_CAT', 'PR_NOME', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13'],
      dtype='str')

### Exibindo os tipos dos dados

In [8]:
df.dtypes

DATA               str
CO_ID            int64
CL_ID            int64
CL_GENERO          str
CL_EC            int64
CL_FHL           int64
CL_SEG             str
PR_ID            int64
PR_CAT             str
PR_NOME            str
Unnamed: 10    float64
Unnamed: 11    float64
Unnamed: 12    float64
Unnamed: 13    float64
dtype: object

### Exibindo a quantidade de linhas e colunas

In [9]:
df.shape

(830000, 14)

### Exibindo informações gerais do arquivo CSV

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  str
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  str
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  str
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  str
 9   PR_NOME      830000 non-null  str
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(5), str(5)
memory usage: 88.7 MB

# Validações e verificação dos valores

### Verificando valores nulos por coluna

In [11]:
df.isnull().sum()

DATA                0
CO_ID               0
CL_ID               0
CL_GENERO           0
CL_EC               0
CL_FHL              0
CL_SEG              0
PR_ID               0
PR_CAT              0
PR_NOME             0
Unnamed: 10    830000
Unnamed: 11    830000
Unnamed: 12    830000
Unnamed: 13    830000
dtype: int64

### Removendo espaços extras dos nomes das colunas

In [12]:
df.columns.str.strip()

print(df.columns.tolist())

['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']

### Vericando valores incorretos

In [13]:
valores_indefinidos = [
    "n/a",
    "n/d",
    "não informado",
    "não disponível",
    "indisponível",
]

contador = 0

for coluna in df.columns:
    for indice, valor in df[coluna].items():
        valor_normalizado = str(valor).strip().lower()

        if any(palavra in valor_normalizado for palavra in valores_indefinidos):
            contador += 1
            print(f"Encontrado na linha {indice}, coluna '{coluna}': {valor}")

print(f"Total de valores encontrados: {contador}")

Encontrado na linha 82, coluna 'PR_CAT': #N/D
Encontrado na linha 223, coluna 'PR_CAT': #N/D
Encontrado na linha 640, coluna 'PR_CAT': #N/D
Encontrado na linha 857, coluna 'PR_CAT': #N/D
Encontrado na linha 917, coluna 'PR_CAT': #N/D
Encontrado na linha 1185, coluna 'PR_CAT': #N/D
Encontrado na linha 1273, coluna 'PR_CAT': #N/D
Encontrado na linha 1303, coluna 'PR_CAT': #N/D
Encontrado na linha 1325, coluna 'PR_CAT': #N/D
Encontrado na linha 1385, coluna 'PR_CAT': #N/D
Encontrado na linha 1542, coluna 'PR_CAT': #N/D
Encontrado na linha 1594, coluna 'PR_CAT': #N/D
Encontrado na linha 1831, coluna 'PR_CAT': #N/D
Encontrado na linha 2061, coluna 'PR_CAT': #N/D
Encontrado na linha 2103, coluna 'PR_CAT': #N/D
Encontrado na linha 2435, coluna 'PR_CAT': #N/D
Encontrado na linha 2589, coluna 'PR_CAT': #N/D
Encontrado na linha 2768, coluna 'PR_CAT': #N/D
Encontrado na linha 3002, coluna 'PR_CAT': #N/D
Encontrado na linha 3010, coluna 'PR_CAT': #N/D
Encontrado na linha 3150, coluna 'PR_CAT': #N/D
Encontrado na linha 3155, coluna 'PR_CAT': #N/D
Encontrado na linha 3636, coluna 'PR_CAT': #N/D
Encontrado na linha 3719, coluna 'PR_CAT': #N/D
Encontrado na linha 4610, coluna 'PR_CAT': #N/D
Encontrado na linha 4733, coluna 'PR_CAT': #N/D
Encontrado na linha 4904, coluna 'PR_CAT': #N/D
Encontrado na linha 4914, coluna 'PR_CAT': #N/D
Encontrado na linha 5022, coluna 'PR_CAT': #N/D
Encontrado na linha 5501, coluna 'PR_CAT': #N/D
Encontrado na linha 5693, coluna 'PR_CAT': #N/D
Encontrado na linha 5844, coluna 'PR_CAT': #N/D
Encontrado na linha 6762, coluna 'PR_CAT': #N/D
Encontrado na linha 6970, coluna 'PR_CAT': #N/D
Encontrado na linha 6986, coluna 'PR_CAT': #N/D
Encontrado na linha 7029, coluna 'PR_CAT': #N/D
Encontrado na linha 7068, coluna 'PR_CAT': #N/D
Encontrado na linha 7773, coluna 'PR_CAT': #N/D
Encontrado na linha 8073, coluna 'PR_CAT': #N/D
Encontrado na linha 8222, coluna 'PR_CAT': #N/D
Encontrado na linha 8443, coluna 'PR_CAT': #N/D
Encontrado na linha 8991, coluna 'PR_CAT': #N/D
Encontrado na linha 9165, coluna 'PR_CAT': #N/D
Encontrado na linha 9383, coluna 'PR_CAT': #N/D
Encontrado na linha 9407, coluna 'PR_CAT': #N/D
Encontrado na linha 9420, coluna 'PR_CAT': #N/D
Encontrado na linha 9477, coluna 'PR_CAT': #N/D
Encontrado na linha 10205, coluna 'PR_CAT': #N/D
Encontrado na linha 10526, coluna 'PR_CAT': #N/D
Encontrado na linha 10785, coluna 'PR_CAT': #N/D
Encontrado na linha 11276, coluna 'PR_CAT': #N/D
Encontrado na linha 11349, coluna 'PR_CAT': #N/D
Encontrado na linha 11372, coluna 'PR_CAT': #N/D
Encontrado na linha 11763, coluna 'PR_CAT': #N/D
Encontrado na linha 11988, coluna 'PR_CAT': #N/D
Encontrado na linha 12140, coluna 'PR_CAT': #N/D
Encontrado na linha 12237, coluna 'PR_CAT': #N/D
Encontrado na linha 12515, coluna 'PR_CAT': #N/D
Encontrado na linha 12923, coluna 'PR_CAT': #N/D
Encontrado na linha 13173, coluna 'PR_CAT': #N/D
Encontrado na linha 13763, coluna 'PR_CAT': #N/D
Encontrado na linha 13798, coluna 'PR_CAT': #N/D
Encontrado na linha 14143, coluna 'PR_CAT': #N/D
Encontrado na linha 14203, coluna 'PR_CAT': #N/D
Encontrado na linha 14228, coluna 'PR_CAT': #N/D
Encontrado na linha 14285, coluna 'PR_CAT': #N/D
Encontrado na linha 14452, coluna 'PR_CAT': #N/D
Encontrado na linha 15113, coluna 'PR_CAT': #N/D
Encontrado na linha 15350, coluna 'PR_CAT': #N/D
Encontrado na linha 16133, coluna 'PR_CAT': #N/D
Encontrado na linha 16140, coluna 'PR_CAT': #N/D
Encontrado na linha 16242, coluna 'PR_CAT': #N/D
Encontrado na linha 16598, coluna 'PR_CAT': #N/D
Encontrado na linha 17069, coluna 'PR_CAT': #N/D
Encontrado na linha 17401, coluna 'PR_CAT': #N/D
Encontrado na linha 17791, coluna 'PR_CAT': #N/D
Encontrado na linha 18574, coluna 'PR_CAT': #N/D
Encontrado na linha 18678, coluna 'PR_CAT': #N/D
Encontrado na linha 19091, coluna 'PR_CAT': #N/D
Encontrado na linha 19480, coluna 'PR_CAT': #N/D
Encontrado na linha 19615, coluna 'PR_CAT': #N/D
Encontrado na linha 19749, coluna 'PR_CAT': #N/D
Encontrado na linha 19784, coluna 'PR_CAT': #N/D
Encontrado na linha 19818, coluna 'PR_CAT': #N/D
Encontrado na linha 19884, coluna 'PR_CAT': #N/D
Encontrado na linha 19963, coluna 'PR_CAT': #N/D
Encontrado na linha 19986, coluna 'PR_CAT': #N/D
Encontrado na linha 20342, coluna 'PR_CAT': #N/D
Encontrado na linha 20432, coluna 'PR_CAT': #N/D
Encontrado na linha 20569, coluna 'PR_CAT': #N/D
Encontrado na linha 20607, coluna 'PR_CAT': #N/D
Encontrado na linha 20884, coluna 'PR_CAT': #N/D
Encontrado na linha 20936, coluna 'PR_CAT': #N/D
Encontrado na linha 21029, coluna 'PR_CAT': #N/D
Encontrado na linha 21306, coluna 'PR_CAT': #N/D
Encontrado na linha 21327, coluna 'PR_CAT': #N/D
Encontrado na linha 21537, coluna 'PR_CAT': #N/D
Encontrado na linha 22093, coluna 'PR_CAT': #N/D
Encontrado na linha 22137, coluna 'PR_CAT': #N/D
Encontrado na linha 22329, coluna 'PR_CAT': #N/D
Encontrado na linha 22400, coluna 'PR_CAT': #N/D
Encontrado na linha 22476, coluna 'PR_CAT': #N/D
Encontrado na linha 22619, coluna 'PR_CAT': #N/D
Encontrado na linha 22669, coluna 'PR_CAT': #N/D
Encontrado na linha 22680, coluna 'PR_CAT': #N/D
Encontrado na linha 22690, coluna 'PR_CAT': #N/D
Encontrado na linha 22717, coluna 'PR_CAT': #N/D
Encontrado na linha 22874, coluna 'PR_CAT': #N/D
Encontrado na linha 22920, coluna 'PR_CAT': #N/D
Encontrado na linha 23594, coluna 'PR_CAT': #N/D
Encontrado na linha 24206, coluna 'PR_CAT': #N/D
Encontrado na linha 24332, coluna 'PR_CAT': #N/D
Encontrado na linha 24418, coluna 'PR_CAT': #N/D
Encontrado na linha 24471, coluna 'PR_CAT': #N/D
Encontrado na linha 24516, coluna 'PR_CAT': #N/D
Encontrado na linha 24727, coluna 'PR_CAT': #N/D
Encontrado na linha 24803, coluna 'PR_CAT': #N/D
Encontrado na linha 24909, coluna 'PR_CAT': #N/D
Encontrado na linha 25043, coluna 'PR_CAT': #N/D
Encontrado na linha 25119, coluna 'PR_CAT': #N/D
Encontrado na linha 25136, coluna 'PR_CAT': #N/D
Encontrado na linha 25454, coluna 'PR_CAT': #N/D
Encontrado na linha 26354, coluna 'PR_CAT': #N/D
Encontrado na linha 26602, coluna 'PR_CAT': #N/D
Encontrado na linha 27215, coluna 'PR_CAT': #N/D
Encontrado na linha 27473, coluna 'PR_CAT': #N/D
Encontrado na linha 27866, coluna 'PR_CAT': #N/D
Encontrado na linha 27975, coluna 'PR_CAT': #N/D
Encontrado na linha 28645, coluna 'PR_CAT': #N/D
Encontrado na linha 28807, coluna 'PR_CAT': #N/D
Encontrado na linha 28903, coluna 'PR_CAT': #N/D
Encontrado na linha 28918, coluna 'PR_CAT': #N/D
Encontrado na linha 29170, coluna 'PR_CAT': #N/D
Encontrado na linha 29191, coluna 'PR_CAT': #N/D
Encontrado na linha 29927, coluna 'PR_CAT': #N/D
Encontrado na linha 29948, coluna 'PR_CAT': #N/D
Encontrado na linha 30028, coluna 'PR_CAT': #N/D
Encontrado na linha 30346, coluna 'PR_CAT': #N/D
Encontrado na linha 30450, coluna 'PR_CAT': #N/D
Encontrado na linha 30706, coluna 'PR_CAT': #N/D
Encontrado na linha 30945, coluna 'PR_CAT': #N/D
Encontrado na linha 31103, coluna 'PR_CAT': #N/D
Encontrado na linha 31217, coluna 'PR_CAT': #N/D
Encontrado na linha 31231, coluna 'PR_CAT': #N/D
Encontrado na linha 31900, coluna 'PR_CAT': #N/D
Encontrado na linha 32313, coluna 'PR_CAT': #N/D
Encontrado na linha 32366, coluna 'PR_CAT': #N/D
Encontrado na linha 32458, coluna 'PR_CAT': #N/D
Encontrado na linha 32768, coluna 'PR_CAT': #N/D
Encontrado na linha 32775, coluna 'PR_CAT': #N/D
Encontrado na linha 32952, coluna 'PR_CAT': #N/D
Encontrado na linha 32992, coluna 'PR_CAT': #N/D
Encontrado na linha 33063, coluna 'PR_CAT': #N/D
Encontrado na linha 33160, coluna 'PR_CAT': #N/D
Encontrado na linha 33350, coluna 'PR_CAT': #N/D
Encontrado na linha 33448, coluna 'PR_CAT': #N/D
Encontrado na linha 33758, coluna 'PR_CAT': #N/D
Encontrado na linha 33790, coluna 'PR_CAT': #N/D
Encontrado na linha 33834, coluna 'PR_CAT': #N/D
Encontrado na linha 34095, coluna 'PR_CAT': #N/D
Encontrado na linha 34135, coluna 'PR_CAT': #N/D
Encontrado na linha 34174, coluna 'PR_CAT': #N/D
Encontrado na linha 34629, coluna 'PR_CAT': #N/D
Encontrado na linha 34696, coluna 'PR_CAT': #N/D
Encontrado na linha 34841, coluna 'PR_CAT': #N/D
Encontrado na linha 35201, coluna 'PR_CAT': #N/D
Encontrado na linha 35265, coluna 'PR_CAT': #N/D
Encontrado na linha 35293, coluna 'PR_CAT': #N/D
Encontrado na linha 35433, coluna 'PR_CAT': #N/D
Encontrado na linha 35723, coluna 'PR_CAT': #N/D
Encontrado na linha 35984, coluna 'PR_CAT': #N/D
Encontrado na linha 36322, coluna 'PR_CAT': #N/D
Encontrado na linha 36664, coluna 'PR_CAT': #N/D
Encontrado na linha 36820, coluna 'PR_CAT': #N/D
Encontrado na linha 36964, coluna 'PR_CAT': #N/D
Encontrado na linha 37129, coluna 'PR_CAT': #N/D
Encontrado na linha 37617, coluna 'PR_CAT': #N/D
Encontrado na linha 37775, coluna 'PR_CAT': #N/D
Encontrado na linha 38008, coluna 'PR_CAT': #N/D
Encontrado na linha 38460, coluna 'PR_CAT': #N/D
Encontrado na linha 38701, coluna 'PR_CAT': #N/D
Encontrado na linha 38789, coluna 'PR_CAT': #N/D
Encontrado na linha 38792, coluna 'PR_CAT': #N/D
Encontrado na linha 39332, coluna 'PR_CAT': #N/D
Encontrado na linha 39392, coluna 'PR_CAT': #N/D
Encontrado na linha 39564, coluna 'PR_CAT': #N/D
Encontrado na linha 40153, coluna 'PR_CAT': #N/D
Encontrado na linha 40283, coluna 'PR_CAT': #N/D
Encontrado na linha 40323, coluna 'PR_CAT': #N/D
Encontrado na linha 40451, coluna 'PR_CAT': #N/D
Encontrado na linha 40701, coluna 'PR_CAT': #N/D
Encontrado na linha 40890, coluna 'PR_CAT': #N/D
Encontrado na linha 41002, coluna 'PR_CAT': #N/D
Encontrado na linha 41093, coluna 'PR_CAT': #N/D
Encontrado na linha 41590, coluna 'PR_CAT': #N/D
Encontrado na linha 41719, coluna 'PR_CAT': #N/D
Encontrado na linha 41875, coluna 'PR_CAT': #N/D
Encontrado na linha 42032, coluna 'PR_CAT': #N/D
Encontrado na linha 42173, coluna 'PR_CAT': #N/D
Encontrado na linha 42435, coluna 'PR_CAT': #N/D
Encontrado na linha 42616, coluna 'PR_CAT': #N/D
Encontrado na linha 43021, coluna 'PR_CAT': #N/D
Encontrado na linha 43129, coluna 'PR_CAT': #N/D
Encontrado na linha 43233, coluna 'PR_CAT': #N/D
Encontrado na linha 43660, coluna 'PR_CAT': #N/D
Encontrado na linha 43989, coluna 'PR_CAT': #N/D
Encontrado na linha 44169, coluna 'PR_CAT': #N/D
Encontrado na linha 44235, coluna 'PR_CAT': #N/D
Encontrado na linha 44425, coluna 'PR_CAT': #N/D
Encontrado na linha 44718, coluna 'PR_CAT': #N/D
Encontrado na linha 45188, coluna 'PR_CAT': #N/D
Encontrado na linha 45386, coluna 'PR_CAT': #N/D
Encontrado na linha 45500, coluna 'PR_CAT': #N/D
Encontrado na linha 45642, coluna 'PR_CAT': #N/D
Encontrado na linha 45854, coluna 'PR_CAT': #N/D
Encontrado na linha 45897, coluna 'PR_CAT': #N/D
Encontrado na linha 46091, coluna 'PR_CAT': #N/D
Encontrado na linha 46106, coluna 'PR_CAT': #N/D
Encontrado na linha 46391, coluna 'PR_CAT': #N/D
Encontrado na linha 46406, coluna 'PR_CAT': #N/D
Encontrado na linha 46438, coluna 'PR_CAT': #N/D
Encontrado na linha 47095, coluna 'PR_CAT': #N/D
Encontrado na linha 47141, coluna 'PR_CAT': #N/D
Encontrado na linha 47240, coluna 'PR_CAT': #N/D
Encontrado na linha 47638, coluna 'PR_CAT': #N/D
Encontrado na linha 47902, coluna 'PR_CAT': #N/D
Encontrado na linha 48394, coluna 'PR_CAT': #N/D
Encontrado na linha 48954, coluna 'PR_CAT': #N/D
Encontrado na linha 49122, coluna 'PR_CAT': #N/D
Encontrado na linha 49169, coluna 'PR_CAT': #N/D
Encontrado na linha 49224, coluna 'PR_CAT': #N/D
Encontrado na linha 49239, coluna 'PR_CAT': #N/D
Encontrado na linha 49443, coluna 'PR_CAT': #N/D
Encontrado na linha 49506, coluna 'PR_CAT': #N/D
Encontrado na linha 49803, coluna 'PR_CAT': #N/D
Encontrado na linha 49806, coluna 'PR_CAT': #N/D
Encontrado na linha 49888, coluna 'PR_CAT': #N/D
Encontrado na linha 49977, coluna 'PR_CAT': #N/D
Encontrado na linha 49987, coluna 'PR_CAT': #N/D
Encontrado na linha 50121, coluna 'PR_CAT': #N/D
Encontrado na linha 50331, coluna 'PR_CAT': #N/D
Encontrado na linha 50486, coluna 'PR_CAT': #N/D
Encontrado na linha 50906, coluna 'PR_CAT': #N/D
Encontrado na linha 51344, coluna 'PR_CAT': #N/D
Encontrado na linha 51623, coluna 'PR_CAT': #N/D
Encontrado na linha 51759, coluna 'PR_CAT': #N/D
Encontrado na linha 52062, coluna 'PR_CAT': #N/D
Encontrado na linha 52220, coluna 'PR_CAT': #N/D
Encontrado na linha 52247, coluna 'PR_CAT': #N/D
Encontrado na linha 52408, coluna 'PR_CAT': #N/D
Encontrado na linha 52414, coluna 'PR_CAT': #N/D
Encontrado na linha 52430, coluna 'PR_CAT': #N/D
Encontrado na linha 52511, coluna 'PR_CAT': #N/D
Encontrado na linha 52808, coluna 'PR_CAT': #N/D
Encontrado na linha 53478, coluna 'PR_CAT': #N/D
Encontrado na linha 53773, coluna 'PR_CAT': #N/D
Encontrado na linha 53872, coluna 'PR_CAT': #N/D
Encontrado na linha 54168, coluna 'PR_CAT': #N/D
Encontrado na linha 54179, coluna 'PR_CAT': #N/D
Encontrado na linha 54432, coluna 'PR_CAT': #N/D
Encontrado na linha 54519, coluna 'PR_CAT': #N/D
Encontrado na linha 54599, coluna 'PR_CAT': #N/D
Encontrado na linha 54628, coluna 'PR_CAT': #N/D
Encontrado na linha 54967, coluna 'PR_CAT': #N/D
Encontrado na linha 55059, coluna 'PR_CAT': #N/D
Encontrado na linha 55179, coluna 'PR_CAT': #N/D
Encontrado na linha 55291, coluna 'PR_CAT': #N/D
Encontrado na linha 55443, coluna 'PR_CAT': #N/D
Encontrado na linha 55519, coluna 'PR_CAT': #N/D
Encontrado na linha 55536, coluna 'PR_CAT': #N/D
Encontrado na linha 55689, coluna 'PR_CAT': #N/D
Encontrado na linha 56083, coluna 'PR_CAT': #N/D
Encontrado na linha 56298, coluna 'PR_CAT': #N/D
Encontrado na linha 56905, coluna 'PR_CAT': #N/D
Encontrado na linha 56941, coluna 'PR_CAT': #N/D
Encontrado na linha 57105, coluna 'PR_CAT': #N/D
Encontrado na linha 57355, coluna 'PR_CAT': #N/D
Encontrado na linha 57838, coluna 'PR_CAT': #N/D
Encontrado na linha 57846, coluna 'PR_CAT': #N/D
Encontrado na linha 57861, coluna 'PR_CAT': #N/D
Encontrado na linha 58166, coluna 'PR_CAT': #N/D
Encontrado na linha 58323, coluna 'PR_CAT': #N/D
Encontrado na linha 58324, coluna 'PR_CAT': #N/D
Encontrado na linha 58401, coluna 'PR_CAT': #N/D
Encontrado na linha 58671, coluna 'PR_CAT': #N/D
Encontrado na linha 58877, coluna 'PR_CAT': #N/D
Encontrado na linha 59287, coluna 'PR_CAT': #N/D
Encontrado na linha 59557, coluna 'PR_CAT': #N/D
Encontrado na linha 59789, coluna 'PR_CAT': #N/D
Encontrado na linha 60002, coluna 'PR_CAT': #N/D
Encontrado na linha 60098, coluna 'PR_CAT': #N/D
Encontrado na linha 60867, coluna 'PR_CAT': #N/D
Encontrado na linha 61008, coluna 'PR_CAT': #N/D
Encontrado na linha 61106, coluna 'PR_CAT': #N/D
Encontrado na linha 61125, coluna 'PR_CAT': #N/D
Encontrado na linha 61246, coluna 'PR_CAT': #N/D
Encontrado na linha 61291, coluna 'PR_CAT': #N/D
Encontrado na linha 61875, coluna 'PR_CAT': #N/D
Encontrado na linha 62003, coluna 'PR_CAT': #N/D
Encontrado na linha 62162, coluna 'PR_CAT': #N/D
Encontrado na linha 62220, coluna 'PR_CAT': #N/D
Encontrado na linha 62427, coluna 'PR_CAT': #N/D
Encontrado na linha 62627, coluna 'PR_CAT': #N/D
Encontrado na linha 62877, coluna 'PR_CAT': #N/D
Encontrado na linha 62912, coluna 'PR_CAT': #N/D
Encontrado na linha 62997, coluna 'PR_CAT': #N/D
Encontrado na linha 62998, coluna 'PR_CAT': #N/D
Encontrado na linha 63435, coluna 'PR_CAT': #N/D
Encontrado na linha 63480, coluna 'PR_CAT': #N/D
Encontrado na linha 63504, coluna 'PR_CAT': #N/D
Encontrado na linha 63535, coluna 'PR_CAT': #N/D
Encontrado na linha 63839, coluna 'PR_CAT': #N/D
Encontrado na linha 64095, coluna 'PR_CAT': #N/D
Encontrado na linha 64226, coluna 'PR_CAT': #N/D
Encontrado na linha 64485, coluna 'PR_CAT': #N/D
Encontrado na linha 64832, coluna 'PR_CAT': #N/D
Encontrado na linha 64860, coluna 'PR_CAT': #N/D
Encontrado na linha 65186, coluna 'PR_CAT': #N/D
Encontrado na linha 65220, coluna 'PR_CAT': #N/D
Encontrado na linha 65295, coluna 'PR_CAT': #N/D
Encontrado na linha 65738, coluna 'PR_CAT': #N/D
Encontrado na linha 66112, coluna 'PR_CAT': #N/D
Encontrado na linha 66212, coluna 'PR_CAT': #N/D
Encontrado na linha 66233, coluna 'PR_CAT': #N/D
Encontrado na linha 66259, coluna 'PR_CAT': #N/D
Encontrado na linha 66441, coluna 'PR_CAT': #N/D
Encontrado na linha 66562, coluna 'PR_CAT': #N/D
Encontrado na linha 66589, coluna 'PR_CAT': #N/D
Encontrado na linha 66625, coluna 'PR_CAT': #N/D
Encontrado na linha 66802, coluna 'PR_CAT': #N/D
Encontrado na linha 66924, coluna 'PR_CAT': #N/D
Encontrado na linha 67014, coluna 'PR_CAT': #N/D
Encontrado na linha 67051, coluna 'PR_CAT': #N/D
Encontrado na linha 67176, coluna 'PR_CAT': #N/D
Encontrado na linha 67180, coluna 'PR_CAT': #N/D
Encontrado na linha 68334, coluna 'PR_CAT': #N/D
Encontrado na linha 68660, coluna 'PR_CAT': #N/D
Encontrado na linha 68777, coluna 'PR_CAT': #N/D
Encontrado na linha 69336, coluna 'PR_CAT': #N/D
Encontrado na linha 69700, coluna 'PR_CAT': #N/D
Encontrado na linha 69720, coluna 'PR_CAT': #N/D
Encontrado na linha 69846, coluna 'PR_CAT': #N/D
Encontrado na linha 70229, coluna 'PR_CAT': #N/D
Encontrado na linha 70362, coluna 'PR_CAT': #N/D
Encontrado na linha 70955, coluna 'PR_CAT': #N/D
Encontrado na linha 71054, coluna 'PR_CAT': #N/D
Encontrado na linha 71268, coluna 'PR_CAT': #N/D
Encontrado na linha 71337, coluna 'PR_CAT': #N/D
Encontrado na linha 71971, coluna 'PR_CAT': #N/D
Encontrado na linha 72214, coluna 'PR_CAT': #N/D
Encontrado na linha 72563, coluna 'PR_CAT': #N/D
Encontrado na linha 72812, coluna 'PR_CAT': #N/D
Encontrado na linha 72906, coluna 'PR_CAT': #N/D
Encontrado na linha 73636, coluna 'PR_CAT': #N/D
Encontrado na linha 73729, coluna 'PR_CAT': #N/D
Encontrado na linha 74087, coluna 'PR_CAT': #N/D
Encontrado na linha 74769, coluna 'PR_CAT': #N/D
Encontrado na linha 74873, coluna 'PR_CAT': #N/D
Encontrado na linha 75562, coluna 'PR_CAT': #N/D
Encontrado na linha 75834, coluna 'PR_CAT': #N/D
Encontrado na linha 75892, coluna 'PR_CAT': #N/D
Encontrado na linha 75953, coluna 'PR_CAT': #N/D
Encontrado na linha 76150, coluna 'PR_CAT': #N/D
Encontrado na linha 76334, coluna 'PR_CAT': #N/D
Encontrado na linha 76470, coluna 'PR_CAT': #N/D
Encontrado na linha 76631, coluna 'PR_CAT': #N/D
Encontrado na linha 76854, coluna 'PR_CAT': #N/D
Encontrado na linha 76925, coluna 'PR_CAT': #N/D
Encontrado na linha 78156, coluna 'PR_CAT': #N/D
Encontrado na linha 78201, coluna 'PR_CAT': #N/D
Encontrado na linha 78230, coluna 'PR_CAT': #N/D
Encontrado na linha 78402, coluna 'PR_CAT': #N/D
Encontrado na linha 78712, coluna 'PR_CAT': #N/D
Encontrado na linha 78928, coluna 'PR_CAT': #N/D
Encontrado na linha 79309, coluna 'PR_CAT': #N/D
Encontrado na linha 80552, coluna 'PR_CAT': #N/D
Encontrado na linha 80922, coluna 'PR_CAT': #N/D
Encontrado na linha 81057, coluna 'PR_CAT': #N/D
Encontrado na linha 81164, coluna 'PR_CAT': #N/D
Encontrado na linha 81171, coluna 'PR_CAT': #N/D
Encontrado na linha 81201, coluna 'PR_CAT': #N/D
Encontrado na linha 81664, coluna 'PR_CAT': #N/D
Encontrado na linha 81920, coluna 'PR_CAT': #N/D
Encontrado na linha 82236, coluna 'PR_CAT': #N/D
Encontrado na linha 82245, coluna 'PR_CAT': #N/D
Encontrado na linha 82523, coluna 'PR_CAT': #N/D
Encontrado na linha 82607, coluna 'PR_CAT': #N/D
Encontrado na linha 82844, coluna 'PR_CAT': #N/D
Encontrado na linha 82934, coluna 'PR_CAT': #N/D
Encontrado na linha 83054, coluna 'PR_CAT': #N/D
Encontrado na linha 83714, coluna 'PR_CAT': #N/D
Encontrado na linha 83902, coluna 'PR_CAT': #N/D
Encontrado na linha 83927, coluna 'PR_CAT': #N/D
Encontrado na linha 84567, coluna 'PR_CAT': #N/D
Encontrado na linha 84694, coluna 'PR_CAT': #N/D
Encontrado na linha 85048, coluna 'PR_CAT': #N/D
Encontrado na linha 85183, coluna 'PR_CAT': #N/D
Encontrado na linha 85812, coluna 'PR_CAT': #N/D
Encontrado na linha 86178, coluna 'PR_CAT': #N/D
Encontrado na linha 86521, coluna 'PR_CAT': #N/D
Encontrado na linha 87179, coluna 'PR_CAT': #N/D
Encontrado na linha 88074, coluna 'PR_CAT': #N/D
Encontrado na linha 88330, coluna 'PR_CAT': #N/D
Encontrado na linha 88948, coluna 'PR_CAT': #N/D
Encontrado na linha 89434, coluna 'PR_CAT': #N/D
Encontrado na linha 89802, coluna 'PR_CAT': #N/D
Encontrado na linha 89821, coluna 'PR_CAT': #N/D
Encontrado na linha 89881, coluna 'PR_CAT': #N/D
Encontrado na linha 89948, coluna 'PR_CAT': #N/D

### Verificando linhas duplicadas

In [14]:
duplicadas = df[df.duplicated(keep="first")]
    
print("Quantidade de linhas duplicadas:", df.duplicated().sum())

Quantidade de linhas duplicadas: 96553

### Verificando datas vazias

In [15]:
print("Quantidade de datas vazias:", df["DATA"].isnull().sum())

Quantidade de datas vazias: 0

### Verificando datas inválidas

In [16]:
data_valida = r"^\d{2}/\d{2}/\d{4}$"

data_invalida = (
    df["DATA"].notna()
    & ~df["DATA"].astype(str).str.strip().str.match(data_valida, na=False)
)

print("Datas inválidas:")
print(df[data_invalida])

Datas inválidas:
Empty DataFrame
Columns: [DATA, CO_ID, CL_ID, CL_GENERO, CL_EC, CL_FHL, CL_SEG, PR_ID, PR_CAT, PR_NOME, Unnamed: 10, Unnamed: 11, Unnamed: 12, Unnamed: 13]
Index: []

### Verificando valores vazios

In [17]:
for coluna in df.columns:
    vazios = (
        df[coluna].isnull()
        | df[coluna].astype(str).str.strip().eq("")
    )

    quantidade_vazias = vazios.sum()

    if quantidade_vazias > 0:
        print(f"{coluna}: {quantidade_vazias} de linhas vazias")
    else:
        print(f"{coluna}: Nenhuma linha vazia encontrada")

DATA: Nenhuma linha vazia encontrada
CO_ID: Nenhuma linha vazia encontrada
CL_ID: Nenhuma linha vazia encontrada
CL_GENERO: Nenhuma linha vazia encontrada
CL_EC: Nenhuma linha vazia encontrada
CL_FHL: Nenhuma linha vazia encontrada
CL_SEG: Nenhuma linha vazia encontrada
PR_ID: Nenhuma linha vazia encontrada
PR_CAT: Nenhuma linha vazia encontrada
PR_NOME: Nenhuma linha vazia encontrada
Unnamed: 10: 830000 de linhas vazias
Unnamed: 11: 830000 de linhas vazias
Unnamed: 12: 830000 de linhas vazias
Unnamed: 13: 830000 de linhas vazias

# Tratamento e limpeza dos valores

### Preenchendo células com valores incorretos

In [18]:
valores_indefinidos = [
    "n/a",
    "n/d",
    "não informado",
    "não disponível",
    "indisponível",
]

contador = 0

for coluna in df.columns:
    for indice, valor in df[coluna].items():
        valor_normalizado = str(valor).strip().lower()

        if any(palavra in valor_normalizado for palavra in valores_indefinidos):
            contador += 1
            df.loc[indice, coluna] = "SEM CATEGORIA"

print(f"Total de valores indefinidos encontrados: {contador}")

Total de valores indefinidos encontrados: 7300

### Preenchendo células com valores nulos/vazios

In [ ]:
quantidade_vazias = df.isnull().sum().sum()

if quantidade_vazias > 0:
    df = df.fillna("SEM CATEGORIA")
    print("Quantidade de células preenchidas:", quantidade_vazias)
else:
    print("Nenhum valor vazio encontrado.")

# Obs.: Preferi preencher as colunas vazias do que excluí-las por inteiro por ser considerada uma prática pouco comum.

Quantidade de células preenchidas: 3320000

### Eliminando linhas duplicadas e salvando em um novo arquivo

In [20]:
duplicadas = df[df.duplicated()]

print("Quantidade de linhas duplicadas eliminadas:", df.duplicated().sum())

df = df.drop_duplicates()

df.to_csv("base_varejo_limpa.csv", sep=";", index=False)

Quantidade de linhas duplicadas eliminadas: 96553

### Convertendo a coluna DATA de string para DATETIME

In [21]:
df["DATA"] = pd.to_datetime(df["DATA"], dayfirst=True)

linhas_erro = df["DATA"].isnull().sum()

print(f"Quantidade de linhas com erro: {linhas_erro}")
print(f"Coluna 'DATA' convertida para o tipo: {df['DATA'].dtype}")

Quantidade de linhas com erro: 0
Coluna 'DATA' convertida para o tipo: datetime64[us]

### Exibindo os tipos dos dados após conversão

In [22]:
df.dtypes

DATA           datetime64[us]
CO_ID                   int64
CL_ID                   int64
CL_GENERO                 str
CL_EC                   int64
CL_FHL                  int64
CL_SEG                    str
PR_ID                   int64
PR_CAT                    str
PR_NOME                   str
Unnamed: 10            object
Unnamed: 11            object
Unnamed: 12            object
Unnamed: 13            object
dtype: object

### Salvando um CSV novo "limpo"

In [23]:
df.to_csv("base_varejo_limpa.csv", sep=";", index=False)

### Carregando o novo arquivo CSV localmente

In [24]:
df = pd.read_csv("base_varejo_limpa.csv", sep=";", encoding="utf-8")

### Verificando linhas restantes

In [25]:
print("Quantidade de linhas restantes:", len(df))

Quantidade de linhas restantes: 733447

# Estatísticas da coluna CL_FHL (Quantidade de filhos dos clientes)

### Média de filhos dos clientes

In [26]:
print(df["CL_FHL"].mean().round(2))

1.15

### Mediana de filhos dos clientes

In [27]:
print(df["CL_FHL"].median())

0.0

### Desvio padrão entre clientes

In [28]:
print(df["CL_FHL"].std().round(2))

1.42

### Quantidade de filhos mais comum dos clientes

In [29]:
print(df["CL_FHL"].mode()[0])

0

### Maior(máximo) número de filhos

In [30]:
print(df["CL_FHL"].max())

4

### Menor(mínimo) número de filhos

In [31]:
print(df["CL_FHL"].min())

0

### Contagem da coluna CL_FHL

In [32]:
print(df["CL_FHL"].count())

733447

### Quartis da coluna CL_FHL

In [33]:
q1 = df["CL_FHL"].quantile(0.25)
q2 = df["CL_FHL"].quantile(0.50)
q3 = df["CL_FHL"].quantile(0.75)

print("1º Quartil (Q1):", q1)
print("2º Quartil (Q2):", q2)
print("3º Quartil (Q3):", q3)

1º Quartil (Q1): 0.0
2º Quartil (Q2): 0.0
3º Quartil (Q3): 2.0

### Utilizando "describe" para mostrar as estatísticas de forma unificada

In [34]:
print(df["CL_FHL"].describe().round(2))

count    733447.00
mean          1.15
std           1.42
min           0.00
25%           0.00
50%           0.00
75%           2.00
max           4.00
Name: CL_FHL, dtype: float64

### Estatísticas da quantidade "número de filhos dos clientes"

In [35]:
print(df["CL_FHL"].value_counts().sort_index())

CL_FHL
0    384986
1     90845
2     94168
3     92407
4     71041
Name: count, dtype: int64

# Explorando padrões de agrupamento com "groupby"

### Descobrindo o gênero que mais comprou por categoria

In [36]:
print(df.groupby(["PR_CAT", "CL_GENERO"])["PR_NOME"].count().reset_index())

           PR_CAT CL_GENERO  PR_NOME
0      ACESSORIOS         F     6839
1      ACESSORIOS         M     6032
2       ALIMENTOS         F   200274
3       ALIMENTOS         M   183923
4         BEBIDAS         F    19764
5         BEBIDAS         M    18500
6         HIGIENE         F    71721
7         HIGIENE         M    65981
8         LIMPEZA         F    67328
9         LIMPEZA         M    61304
10            PET         F    14809
11            PET         M    13744
12  SEM CATEGORIA         F     1692
13  SEM CATEGORIA         M     1536

### Descobrindo o produto que mais vendeu por gênero de cada categoria

In [37]:
print(df.groupby(["PR_CAT", "PR_NOME"])["CL_GENERO"].count().reset_index())

            PR_CAT                 PR_NOME  CL_GENERO
0       ACESSORIOS                 CHUPETA       6464
1       ACESSORIOS                MORDEDOR       6407
2        ALIMENTOS                 ABACATE       3232
3        ALIMENTOS                 ABACAXI       3239
4        ALIMENTOS            ACHOCOLATADO       3243
..             ...                     ...        ...
113            PET    RACAO SECA PARA CAES       6434
114            PET   RACAO SECA PARA GATOS       6343
115            PET   RACAO UMIDA PARA CAES       6345
116            PET  RACAO UMIDA PARA GATOS       6233
117  SEM CATEGORIA           SEM CATEGORIA       3228

[118 rows x 3 columns]

### Descobrindo o volume de vendas de cada produto por segmentação social

In [38]:
print(df.groupby(["PR_NOME", "CL_SEG"])["PR_CAT"].count().reset_index())

      PR_NOME CL_SEG  PR_CAT
0     ABACATE      A     262
1     ABACATE      B    2049
2     ABACATE      C     921
3     ABACAXI      A     255
4     ABACAXI      B    2088
..        ...    ...     ...
349       UVA      B    4108
350       UVA      C    1809
351  VASSOURA      A     508
352  VASSOURA      B    4095
353  VASSOURA      C    1813

[354 rows x 3 columns]